# Site settings
title: Yiguid Site
email: yiguid@gmail.com
description: "Longing for love, search for knowledge, pity for suffering"
baseurl: ""
url: "http://yiguid.com"
twitter_username: yiguidcom
github_username:  yiguid
theme: jekyll-theme-hacker

# Build settings
markdown: kramdown
permalink: pretty
